server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/shopdb}
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-disabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  cors:
    origins: ${CORS_ORIGINS:http://localhost:3000}
  jwt:
    secret: ${JWT_SECRET:change-me-super-long-secret-32+chars-minimum-please!!!}
    expiration-min: 60


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

